export const staticSongs = [
  {
    id: '1',
    url: 'https://rntp.dev/example/Longing.mp3',
    title: 'Longing',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Longing.jpeg',
    duration: 143,
    album: '',
    genre: '',
  },
  {
    id: '2',
    url: 'https://rntp.dev/example/Soul%20Searching.mp3',
    title: 'Soul Searching (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Soul%20Searching.jpeg',
    duration: 77,
    album: '',
    genre: '',
  },
  {
    id: '3',
    url: 'https://rntp.dev/example/Lullaby%20(Demo).mp3',
    title: 'Lullaby (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Lullaby%20(Demo).jpeg',
    duration: 71,
    album: '',
    genre: '',
  },
  {
    id: '4',
    url: 'https://rntp.dev/example/Rhythm%20City%20(Demo).mp3',
    title: 'Rhythm City (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Rhythm%20City%20(Demo).jpeg',
    duration: 106,
    album: '',
    genre: '',
  },
  {
    id: '5',
    url: 'https://rntp.dev/example/hls/whip/playlist.m3u8',
    title: 'Whip',
    artist: 'prazkhanal',
    cover: 'https://rntp.dev/example/hls/whip/whip.jpeg',
    duration: 1111,
    album: '',
    genre: '',
  },
  {
    id: '6',
    url: 'https://ais-sa5.cdnstream1.com/b75154_128mp3',
    title: 'Smooth Jazz 24/7',
    artist: 'New York, NY',
    cover: 'https://rntp.dev/example/smooth-jazz-24-7.jpeg',
    duration: 222,
    album: '',
    genre: '',
  },
  {
    id: '7',
    url: 'https://traffic.libsyn.com/atpfm/atp545.mp3',
    title: 'Chapters',
    artist: 'Monty Python',
    cover: 'https://picsum.photos/id/5/200/300',
    duration: 111,
    album: '',
    genre: '',
  },
  {
    id: '8',
    url: 'https://kut.streamguys1.com/kutx-app.aac?listenerId=123456784123',
    title: 'KUTX',
    artist: 'Bob Don',
    cover: 'https://picsum.photos/id/6/200/300',
    duration: 111,
    album: '',
    genre: '',
  },
];
