export const staticSongs = [
  // {
  //   id: '1',
  //   title: 'Aenean is a good boy leo',
  //   artist: 'Utinc Tincidunt',
  //   cover: 'https://picsum.photos/id/1/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '2',
  //   title: 'In the house of turpis',
  //   artist: 'Aenean Parero',
  //   cover: 'https://picsum.photos/id/2/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '3',
  //   title: 'Lorem has some Ipsum',
  //   artist: 'Phasellus John',
  //   cover: 'https://picsum.photos/id/3/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '4',
  //   title: 'Ghost in the vally of Death',
  //   artist: 'Devil & John',
  //   cover: 'https://picsum.photos/id/4/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '5',
  //   title: 'You do you!',
  //   artist: 'Phill Carter',
  //   cover: 'https://picsum.photos/id/5/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '6',
  //   title: 'Its you verser you.',
  //   artist: 'The Guru',
  //   cover: 'https://picsum.photos/id/6/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  // {
  //   id: '7',
  //   title: 'You have to go and I am coming.',
  //   artist: 'Cannon Music',
  //   cover: 'https://picsum.photos/id/7/200/300',
  //   url: '',
  //   album: '',
  //   duration: 111,
  //   genre: '',
  // },
  {
    id: '8',
    url: 'https://rntp.dev/example/Longing.mp3',
    title: 'Longing',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Longing.jpeg',
    duration: 143,
    album: '',
    genre: '',
  },
  {
    id: '9',
    url: 'https://rntp.dev/example/Soul%20Searching.mp3',
    title: 'Soul Searching (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Soul%20Searching.jpeg',
    duration: 77,
    album: '',
    genre: '',
  },
  {
    id: '10',
    url: 'https://rntp.dev/example/Lullaby%20(Demo).mp3',
    title: 'Lullaby (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Lullaby%20(Demo).jpeg',
    duration: 71,
    album: '',
    genre: '',
  },
  {
    id: '11',
    url: 'https://rntp.dev/example/Rhythm%20City%20(Demo).mp3',
    title: 'Rhythm City (Demo)',
    artist: 'David Chavez',
    cover: 'https://rntp.dev/example/Rhythm%20City%20(Demo).jpeg',
    duration: 106,
    album: '',
    genre: '',
  },
  {
    id: '12',
    url: 'https://rntp.dev/example/hls/whip/playlist.m3u8',
    title: 'Whip',
    artist: 'prazkhanal',
    cover: 'https://rntp.dev/example/hls/whip/whip.jpeg',
    duration: 1111,
    album: '',
    genre: '',
  },
  {
    id: '13',
    url: 'https://ais-sa5.cdnstream1.com/b75154_128mp3',
    title: 'Smooth Jazz 24/7',
    artist: 'New York, NY',
    cover: 'https://rntp.dev/example/smooth-jazz-24-7.jpeg',
    duration: 222,
    album: '',
    genre: '',
  },
  {
    id: '14',
    url: 'https://traffic.libsyn.com/atpfm/atp545.mp3',
    title: 'Chapters',
    artist: 'Monty Python',
    cover: 'https://picsum.photos/id/5/200/300',
    duration: 111,
    album: '',
    genre: '',
  },
  {
    id: '15',
    url: 'https://kut.streamguys1.com/kutx-app.aac?listenerId=123456784123',
    title: 'KUTX',
    artist: 'Bob Don',
    cover: 'https://picsum.photos/id/5/200/300',
    duration: 111,
    album: '',
    genre: '',
  },
];
